import turtle
sheldon = turtle.Turtle()
sheldon.shape('turtle')

sheldon.pendown
sheldon.color("grey")
sheldon.pencolor("grey")
sheldon.begin_fill()
sheldon.goto(200,200)
sheldon.goto(200,-200)
sheldon.goto(-200,-200)
sheldon.goto(-200,200)
sheldon.goto(200,200)
sheldon.end_fill()

sheldon.penup()
sheldon.goto(-200,150)
sheldon.forward(20)
sheldon.color("yellow")
sheldon.write("Hello! I'm Sheldon and I'll tell you why we need gender neutral bathrooms")
sheldon.backward(20)

sheldon.penup()
sheldon.goto(-200,100)
sheldon.forward(20)
sheldon.color("white")
sheldon.write("There are currently over 60 different genders, but most places still")
sheldon.goto(-200,90)
sheldon.forward(20)
sheldon.write("have bathrooms designated for men and women.")
sheldon.backward(20)

sheldon.penup()
sheldon.goto(-200,50)
sheldon.forward(20)
sheldon.color("purple")
sheldon.write("We should promote single, gender neutral bathrooms so we can include all genders.")
sheldon.backward(20)

sheldon.penup()
sheldon.goto(-200,0)
sheldon.forward(20)
sheldon.color("black")
sheldon.write("The bathrooms will be the size of 2 handicapped stalls combined, and will have a")
sheldon.goto(-200,-10)
sheldon.write("standard wooden bathroom door, with a lock.")
sheldon.backward(20)

sheldon.penup()
sheldon.goto(-200,-50)
sheldon.forward(20)
sheldon.color("violet")
sheldon.write("Inside each bathroom, there will be railings, automatic toilets, automatic soap")
sheldon.goto(-200,-60)
sheldon.write("dispensers, automatic sinks, and automatic paper towel dispensers.")
sheldon.backward(20)

sheldon.penup()
sheldon.goto(-200,-100)
sheldon.forward(20)
sheldon.color("white")
sheldon.write("The main goal of these bathrooms is to make every gender feel included, and")
sheldon.goto(-200,-110)
sheldon.write("having gender neutral bathrooms indicates progress")
sheldon.backward(20)

sheldon.penup()
sheldon.goto(-200,-150)
sheldon.forward(20)
sheldon.color("dark green")
sheldon.write("Thanks for listening!!!")
sheldon.backward(20)
